# Generated by Django 2.1.5 on 2020-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_updateabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCertifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='myweb/images')),
            ],
        ),
    ]
