# Generated by Django 2.1.5 on 2020-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20201230_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecertiphoto',
            name='desc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
