# Generated by Django 2.1.5 on 2021-01-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_updatecertiphoto_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc3', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
