# Generated by Django 2.1.5 on 2021-01-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_updatehomephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='iam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.CharField(max_length=120)),
            ],
        ),
    ]
