# Generated by Django 2.1.5 on 2021-01-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_auto_20210103_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateaboutphoto',
            name='img1',
        ),
        migrations.AddField(
            model_name='updateaboutphoto',
            name='img3',
            field=models.ImageField(default='', upload_to='myweb/images'),
        ),
    ]
