# Generated by Django 2.1.5 on 2021-01-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_auto_20210103_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateProgressBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('progress', models.CharField(max_length=100)),
            ],
        ),
    ]
