# Generated by Django 2.1.5 on 2021-01-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0013_updateprogressbar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateSkillphoto',
        ),
    ]
