# Generated by Django 2.1.5 on 2021-01-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0016_auto_20210103_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecolor',
            name='footersvg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='updatecolor',
            name='footertext',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
