# Generated by Django 2.1.5 on 2021-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0017_auto_20210103_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatecolor',
            old_name='txt',
            new_name='NavCont',
        ),
        migrations.AddField(
            model_name='updatecolor',
            name='bodybg',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='updatecolor',
            name='bodytxt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='updatecolor',
            name='iamtext',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
