# Generated by Django 2.1.5 on 2021-01-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0018_auto_20210103_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecolor',
            name='footerbg',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
