# Generated by Django 2.1.5 on 2021-01-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0019_updatecolor_footerbg'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecolor',
            name='next',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='updatecolor',
            name='nextbg',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
