# Generated by Django 2.1.5 on 2021-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0020_auto_20210103_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecolor',
            name='nexthov',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
