# Generated by Django 2.1.5 on 2021-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0021_updatecolor_nexthov'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatehomephoto',
            name='imgmob',
            field=models.ImageField(default='', upload_to='myweb/images'),
        ),
    ]
